#!/usr/bin/env python
#
# Simple script showing how to get a set number of samples from all devices
# connected to a system.

from __future__ import print_function

import sys
import time

from pysmu import Session, Mode


if __name__ == '__main__':
    session = Session()
    session.add_all()

    if not session.devices:
        sys.exit()

    for dev in session.devices:
        dev.channels['A'].mode = Mode.SVMI
        dev.channels['A'].constant(4)
        dev.channels['B'].mode = Mode.SIMV
        dev.channels['B'].constant(-.2)

    session.run(10)

    for dev in session.devices:
        samples = dev.get_samples(10)
        print(samples)

    session.end()
