#!/usr/bin/env python2.7

from __future__ import print_function

import pysmu


if __name__ == '__main__':
    x = pysmu.Smu()
    if x.devices:
        A = x.channels['A']
        A.set_mode('v')
        A.constant(3)
        print(A.get_samples(1000))

        d = x.devices[0]
        print(d.get_samples(10))
        import itertools
        print(list(itertools.islice(d.samples, 10)))
