#!/usr/bin/env python
#
# Simple script showing how to read and write data to a device, use Ctrl-C to exit.

from __future__ import print_function

from signal import signal, SIG_DFL, SIGINT
import random
import time

from pysmu import Session, Mode


def refill_data():
    # fill channels with a static, random integer between 0 and 5
    return [random.randint(0,5)] * 10000
    # fill channels with a static, random float between -0.2 and 0.2
    #return [random.uniform(-0.2,0.2)] * 10000


if __name__ == '__main__':
    # don't throw KeyboardInterrupt on Ctrl-C
    signal(SIGINT, SIG_DFL)

    session = Session()

    if session.devices:
        dev = session.devices[0]
        chan_a = dev.channels['A']
        chan_b = dev.channels['B']
        chan_a.mode = Mode.SVMI
        chan_b.mode = Mode.SVMI
        #chan_a.mode = Mode.SIMV
        #chan_b.mode = Mode.SIMV
        session.start(0)
        while True:
            chan_a.write(refill_data())
            chan_b.write(refill_data())
            samples = dev.read(10000)
            for x in samples:
                print("{:6f} {:6f} {:6f} {:6f}".format(x[0][0], x[0][1], x[1][0], x[1][1]))
    else:
        print('no devices attached')
