#!/usr/bin/env python
#
# Simple script showing how to stream data from a device, use Ctrl-C to exit.

from __future__ import print_function

from signal import signal, SIG_DFL, SIGINT
import time

from pysmu import Session


if __name__ == '__main__':
    # don't throw KeyboardInterrupt on Ctrl-C
    signal(SIGINT, SIG_DFL)

    session = Session()
    session.add_all()

    if session.devices:
        dev = session.devices[0]
        session.configure()
        session.start(0)
        while True:
            samples = dev.read(1024)
            for x in samples:
                print("{:6f} {:6f} {:6f} {:6f}".format(*x))
    else:
        print('no devices attached')
